version: "3.8"
services:
  phonebookdb:
    container_name: phonebookdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - phonebookdb_volume:/data/db
  reportdb:
    container_name: reportdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - report_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=phonebook
      - POSTGRES_PASSWORD=*Password12*
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  phonebook.api:
    container_name: phonebook.api
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - RabbitMQUrl=rabbitmq
      - DatabaseSettings:ConnectionString=mongodb://phonebookdb:27017
    ports:
      - "5010:80"
    depends_on:
      - phonebookdb
  datacapture.api:
    container_name: datacapture.api
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - RabbitMQUrl=rabbitmq
      - ConnectionString=User ID=phonebook;Password=*Password12*;Server=reportdb;Database=phonebook;Integrated Security=true;Pooling=true;
    ports:
      - "5099:80"
    depends_on:
      - reportdb  
  report.api:
    container_name: report.api
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - RabbitMQUrl=rabbitmq
      - ConnectionString=User ID=phonebook;Password=*Password12*;Server=reportdb;Database=phonebook;Integrated Security=true;Pooling=true;
    ports:
      - "5020:80"
    depends_on:
      - reportdb  
  gateway:
    container_name: gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Services:phonebook:DownstreamPath=http://phonebook.api
      - Services:report:DownstreamPath=http://report.api
    ports:
      - "5000:80"
    depends_on:
      - phonebook.api
      - datacapture.api
      - report.api
      